#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    ## Works: ./waf clean build -j1
    ## Works: ./waf clean build --targets=test3 -j1
    bld.program(target='test3', source='main.c', includes='.', use='dummy_h')
    bld(target='dummy.h', source='dummy.h.in', rule='sleep 1 && cp ${SRC} ${TGT}',
        features='use', name='dummy_h', ext_out=['.h'])
